"""Restricted foreign key operations

Revision ID: 0d606389ff62
Revises: 903e41fdc11a
Create Date: 2025-08-11 15:53:04.423266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d606389ff62'
down_revision: Union[str, Sequence[str], None] = '903e41fdc11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('class_sections_class_id_fkey'), 'class_sections', type_='foreignkey')
    op.drop_constraint(op.f('class_sections_school_id_fkey'), 'class_sections', type_='foreignkey')
    op.drop_constraint(op.f('class_sections_section_id_fkey'), 'class_sections', type_='foreignkey')
    op.create_foreign_key(None, 'class_sections', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'class_sections', 'sections', ['section_id'], ['section_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'class_sections', 'classes', ['class_id'], ['class_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(op.f('classes_school_id_fkey'), 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('parents', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('parents_school_id_fkey'), 'parents', type_='foreignkey')
    op.create_foreign_key(None, 'parents', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.add_column('schools', sa.Column('address', sa.String(), nullable=True))
    op.drop_constraint(op.f('sections_school_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(op.f('student_class_reg_no_fkey'), 'student_class', type_='foreignkey')
    op.drop_constraint(op.f('student_class_school_id_fkey'), 'student_class', type_='foreignkey')
    op.drop_constraint(op.f('student_class_class_section_id_fkey'), 'student_class', type_='foreignkey')
    op.create_foreign_key(None, 'student_class', 'students', ['reg_no'], ['reg_no'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'student_class', 'class_sections', ['class_section_id'], ['class_section_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'student_class', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('student_parent', 'reg_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_parent', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('student_parent_parent_id_fkey'), 'student_parent', type_='foreignkey')
    op.drop_constraint(op.f('student_parent_reg_no_fkey'), 'student_parent', type_='foreignkey')
    op.create_foreign_key(None, 'student_parent', 'parents', ['parent_id'], ['parent_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'student_parent', 'students', ['reg_no'], ['reg_no'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(op.f('students_school_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(op.f('subject_class_class_section_id_fkey'), 'subject_class', type_='foreignkey')
    op.drop_constraint(op.f('subject_class_subject_id_fkey'), 'subject_class', type_='foreignkey')
    op.drop_constraint(op.f('subject_class_school_id_fkey'), 'subject_class', type_='foreignkey')
    op.create_foreign_key(None, 'subject_class', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'subject_class', 'class_sections', ['class_section_id'], ['class_section_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'subject_class', 'subjects', ['subject_id'], ['subject_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(op.f('subjects_school_id_fkey'), 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(op.f('teacher_class_subjects_subject_id_fkey'), 'teacher_class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('teacher_class_subjects_school_id_fkey'), 'teacher_class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('teacher_class_subjects_teacher_id_fkey'), 'teacher_class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('teacher_class_subjects_class_section_id_fkey'), 'teacher_class_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_class_subjects', 'teachers', ['teacher_id'], ['teacher_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'teacher_class_subjects', 'class_sections', ['class_section_id'], ['class_section_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'teacher_class_subjects', 'subjects', ['subject_id'], ['subject_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'teacher_class_subjects', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(op.f('teachers_school_id_fkey'), 'teachers', type_='foreignkey')
    op.create_foreign_key(None, 'teachers', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_foreign_key(op.f('teachers_school_id_fkey'), 'teachers', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'teacher_class_subjects', type_='foreignkey')
    op.drop_constraint(None, 'teacher_class_subjects', type_='foreignkey')
    op.drop_constraint(None, 'teacher_class_subjects', type_='foreignkey')
    op.drop_constraint(None, 'teacher_class_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_class_subjects_class_section_id_fkey'), 'teacher_class_subjects', 'class_sections', ['class_section_id'], ['class_section_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('teacher_class_subjects_teacher_id_fkey'), 'teacher_class_subjects', 'teachers', ['teacher_id'], ['teacher_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('teacher_class_subjects_school_id_fkey'), 'teacher_class_subjects', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('teacher_class_subjects_subject_id_fkey'), 'teacher_class_subjects', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(op.f('subjects_school_id_fkey'), 'subjects', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'subject_class', type_='foreignkey')
    op.drop_constraint(None, 'subject_class', type_='foreignkey')
    op.drop_constraint(None, 'subject_class', type_='foreignkey')
    op.create_foreign_key(op.f('subject_class_school_id_fkey'), 'subject_class', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('subject_class_subject_id_fkey'), 'subject_class', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('subject_class_class_section_id_fkey'), 'subject_class', 'class_sections', ['class_section_id'], ['class_section_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_school_id_fkey'), 'students', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'student_parent', type_='foreignkey')
    op.drop_constraint(None, 'student_parent', type_='foreignkey')
    op.create_foreign_key(op.f('student_parent_reg_no_fkey'), 'student_parent', 'students', ['reg_no'], ['reg_no'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_parent_parent_id_fkey'), 'student_parent', 'parents', ['parent_id'], ['parent_id'], ondelete='CASCADE')
    op.alter_column('student_parent', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_parent', 'reg_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'student_class', type_='foreignkey')
    op.drop_constraint(None, 'student_class', type_='foreignkey')
    op.drop_constraint(None, 'student_class', type_='foreignkey')
    op.create_foreign_key(op.f('student_class_class_section_id_fkey'), 'student_class', 'class_sections', ['class_section_id'], ['class_section_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_class_school_id_fkey'), 'student_class', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_class_reg_no_fkey'), 'student_class', 'students', ['reg_no'], ['reg_no'], ondelete='CASCADE')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_school_id_fkey'), 'sections', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.drop_column('schools', 'address')
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.create_foreign_key(op.f('parents_school_id_fkey'), 'parents', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.alter_column('parents', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key(op.f('classes_school_id_fkey'), 'classes', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'class_sections', type_='foreignkey')
    op.drop_constraint(None, 'class_sections', type_='foreignkey')
    op.drop_constraint(None, 'class_sections', type_='foreignkey')
    op.create_foreign_key(op.f('class_sections_section_id_fkey'), 'class_sections', 'sections', ['section_id'], ['section_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('class_sections_school_id_fkey'), 'class_sections', 'schools', ['school_id'], ['school_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('class_sections_class_id_fkey'), 'class_sections', 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
