"""changed parent model email field and added school id in student_parent

Revision ID: 0e46c1101fcc
Revises: 8732ed725dc1
Create Date: 2025-08-12 18:40:07.511286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e46c1101fcc'
down_revision: Union[str, Sequence[str], None] = '8732ed725dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'parents', ['email'])
    op.add_column('student_parent', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student_parent', 'schools', ['school_id'], ['school_id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_parent', type_='foreignkey')
    op.drop_column('student_parent', 'school_id')
    op.alter_column('student_class', 'student_class_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'parents', type_='unique')
    # ### end Alembic commands ###
