"""disabled nullable for class_section

Revision ID: 1162d4c3788d
Revises: 0d606389ff62
Create Date: 2025-08-11 16:19:30.794611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1162d4c3788d'
down_revision: Union[str, Sequence[str], None] = '0d606389ff62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_sections', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('class_sections', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('class_sections', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('classes', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sections', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('classes', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_sections', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_sections', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_sections', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
