"""add unique constraint to teacher_class_subjects

Revision ID: 150b28f8d131
Revises: 570bc0fa0e28
Create Date: 2025-08-19 19:38:35.556177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150b28f8d131'
down_revision: Union[str, Sequence[str], None] = '570bc0fa0e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_unique_constraint('unique_teacher_class_subject', 'teacher_class_subjects', ['school_id', 'teacher_id', 'class_section_id', 'subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_teacher_class_subject', 'teacher_class_subjects', type_='unique')
    
    # ### end Alembic commands ###
