"""Added not nullable constraints

Revision ID: 16e51b29ecd5
Revises: 84bed183bddf
Create Date: 2025-08-07 16:38:20.226069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e51b29ecd5'
down_revision: Union[str, Sequence[str], None] = '84bed183bddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'class_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('parents', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('parents', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('parents', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('parents', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('parents', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sections', 'section_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student_class', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_class', 'reg_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_class', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject_class', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject_class', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject_class', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subjects', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subjects', 'subject_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teacher_class_subjects', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teacher_class_subjects', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teacher_class_subjects', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teacher_class_subjects', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teachers', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teacher_class_subjects', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teacher_class_subjects', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teacher_class_subjects', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teacher_class_subjects', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subjects', 'subject_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subjects', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject_class', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject_class', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject_class', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_class', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_class', 'reg_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_class', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sections', 'section_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('parents', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('parents', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('parents', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('parents', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('parents', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('classes', 'class_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
