"""sc_id -> student_claas_id

Revision ID: 241f1528fb85
Revises: 16e51b29ecd5
Create Date: 2025-08-09 23:17:37.723111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241f1528fb85'
down_revision: Union[str, Sequence[str], None] = '16e51b29ecd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_class', sa.Column('student_class_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_student_class_sc_id'), table_name='student_class')
    op.create_index(op.f('ix_student_class_student_class_id'), 'student_class', ['student_class_id'], unique=False)
    op.drop_column('student_class', 'sc_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_class', sa.Column('sc_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_student_class_student_class_id'), table_name='student_class')
    op.create_index(op.f('ix_student_class_sc_id'), 'student_class', ['sc_id'], unique=False)
    op.drop_column('student_class', 'student_class_id')
    # ### end Alembic commands ###
