"""add unique constraint to subjects

Revision ID: 2f0d8a010937
Revises: 12f0ff2420ba
Create Date: 2025-08-13 16:18:25.171594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0d8a010937'
down_revision: Union[str, Sequence[str], None] = '12f0ff2420ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_unique_constraint('unique_school_subject', 'subjects', ['school_id', 'subject_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_school_subject', 'subjects', type_='unique')
    
    # ### end Alembic commands ###
