"""Initial full schema

Revision ID: 3f261b555d41
Revises: 
Create Date: 2025-08-29 16:40:44.701153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f261b555d41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_index(op.f('ix_schools_school_id'), 'schools', ['school_id'], unique=False)
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_classes_class_id'), 'classes', ['class_id'], unique=False)
    op.create_table('parents',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('parent_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_parents_parent_id'), 'parents', ['parent_id'], unique=False)
    op.create_table('sections',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_sections_section_id'), 'sections', ['section_id'], unique=False)
    op.create_table('students',
    sa.Column('reg_no', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(), nullable=False),
    sa.Column('l_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('admit_date', sa.DateTime(), nullable=True),
    sa.Column('leave_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('reg_no')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_reg_no'), 'students', ['reg_no'], unique=False)
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('school_id', 'subject_name', name='unique_school_subject')
    )
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'school_admin', 'teacher', 'student', 'parent', name='userrole'), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('class_sections',
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('class_section_id')
    )
    op.create_index(op.f('ix_class_sections_class_section_id'), 'class_sections', ['class_section_id'], unique=False)
    op.create_table('student_parent',
    sa.Column('student_parent_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reg_no'], ['students.reg_no'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('student_parent_id')
    )
    op.create_index(op.f('ix_student_parent_student_parent_id'), 'student_parent', ['student_parent_id'], unique=False)
    op.create_table('student_class',
    sa.Column('student_class_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.class_section_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reg_no'], ['students.reg_no'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('student_class_id'),
    sa.UniqueConstraint('school_id', 'reg_no', 'class_section_id', name='unique_student_class')
    )
    op.create_index(op.f('ix_student_class_student_class_id'), 'student_class', ['student_class_id'], unique=False)
    op.create_table('subject_class',
    sa.Column('subject_class_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.class_section_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('subject_class_id'),
    sa.UniqueConstraint('school_id', 'subject_id', 'class_section_id', name='unique_school_subject_class')
    )
    op.create_index(op.f('ix_subject_class_subject_class_id'), 'subject_class', ['subject_class_id'], unique=False)
    op.create_table('teacher_class_subjects',
    sa.Column('teacher_class_subjects', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.class_section_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('teacher_class_subjects'),
    sa.UniqueConstraint('school_id', 'teacher_id', 'class_section_id', 'subject_id', name='unique_teacher_class_subject')
    )
    op.create_index(op.f('ix_teacher_class_subjects_teacher_class_subjects'), 'teacher_class_subjects', ['teacher_class_subjects'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_class_subjects_teacher_class_subjects'), table_name='teacher_class_subjects')
    op.drop_table('teacher_class_subjects')
    op.drop_index(op.f('ix_subject_class_subject_class_id'), table_name='subject_class')
    op.drop_table('subject_class')
    op.drop_index(op.f('ix_student_class_student_class_id'), table_name='student_class')
    op.drop_table('student_class')
    op.drop_index(op.f('ix_student_parent_student_parent_id'), table_name='student_parent')
    op.drop_table('student_parent')
    op.drop_index(op.f('ix_class_sections_class_section_id'), table_name='class_sections')
    op.drop_table('class_sections')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_students_reg_no'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_sections_section_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_parents_parent_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_classes_class_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_schools_school_id'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
