"""Added Google auth attribute in users table

Revision ID: 4baab9146d67
Revises: 3f261b555d41
Create Date: 2025-08-30 18:58:56.627775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4baab9146d67'
down_revision: Union[str, Sequence[str], None] = '3f261b555d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oauth_sub', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['oauth_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'oauth_sub')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
