"""add unique constraint to subject_class

Revision ID: 570bc0fa0e28
Revises: 2f0d8a010937
Create Date: 2025-08-13 17:59:00.373359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570bc0fa0e28'
down_revision: Union[str, Sequence[str], None] = '2f0d8a010937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_unique_constraint('unique_school_subject_class', 'subject_class', ['school_id', 'subject_id', 'class_section_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_school_subject_class', 'subject_class', type_='unique')
    
    # ### end Alembic commands ###
