"""add unique constraint to student_class

Revision ID: 8699b90f238a
Revises: 150b28f8d131
Create Date: 2025-08-19 19:44:35.714314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8699b90f238a'
down_revision: Union[str, Sequence[str], None] = '150b28f8d131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_unique_constraint('unique_student_class', 'student_class', ['school_id', 'reg_no', 'class_section_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_student_class', 'student_class', type_='unique')
    
    # ### end Alembic commands ###
