"""Add auto increment to student_class_id

Revision ID: 8732ed725dc1
Revises: 1162d4c3788d
Create Date: 2025-08-11 19:44:59.929485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8732ed725dc1'
down_revision: Union[str, Sequence[str], None] = '1162d4c3788d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        ALTER TABLE student_class
        ALTER COLUMN student_class_id
        ADD GENERATED BY DEFAULT AS IDENTITY
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        ALTER TABLE student_class
        ALTER COLUMN student_class_id
        DROP IDENTITY IF EXISTS
    """)
