"""Initial full schema

Revision ID: a3aa04f88902
Revises: 
Create Date: 2025-08-05 16:16:42.344580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3aa04f88902'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_index(op.f('ix_schools_school_id'), 'schools', ['school_id'], unique=False)
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_classes_class_id'), 'classes', ['class_id'], unique=False)
    op.create_table('parents',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('parent_id')
    )
    op.create_index(op.f('ix_parents_parent_id'), 'parents', ['parent_id'], unique=False)
    op.create_table('sections',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_sections_section_id'), 'sections', ['section_id'], unique=False)
    op.create_table('students',
    sa.Column('reg_no', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('admit_date', sa.DateTime(), nullable=True),
    sa.Column('leave_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('reg_no')
    )
    op.create_index(op.f('ix_students_reg_no'), 'students', ['reg_no'], unique=False)
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('teacher_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    op.create_table('class_sections',
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('class_section_id')
    )
    op.create_index(op.f('ix_class_sections_class_section_id'), 'class_sections', ['class_section_id'], unique=False)
    op.create_table('student_parent',
    sa.Column('student_parent_id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], ),
    sa.ForeignKeyConstraint(['reg_no'], ['students.reg_no'], ),
    sa.PrimaryKeyConstraint('student_parent_id')
    )
    op.create_index(op.f('ix_student_parent_student_parent_id'), 'student_parent', ['student_parent_id'], unique=False)
    op.create_table('student_class',
    sa.Column('sc_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('reg_no', sa.Integer(), nullable=True),
    sa.Column('class_section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.class_section_id'], ),
    sa.ForeignKeyConstraint(['reg_no'], ['students.reg_no'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('sc_id')
    )
    op.create_index(op.f('ix_student_class_sc_id'), 'student_class', ['sc_id'], unique=False)
    op.create_table('subject_class',
    sa.Column('subject_class_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('class_section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.class_section_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('subject_class_id')
    )
    op.create_index(op.f('ix_subject_class_subject_class_id'), 'subject_class', ['subject_class_id'], unique=False)
    op.create_table('teacher_class_subjects',
    sa.Column('teacher_class_subjects', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('class_section_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.class_section_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('teacher_class_subjects')
    )
    op.create_index(op.f('ix_teacher_class_subjects_teacher_class_subjects'), 'teacher_class_subjects', ['teacher_class_subjects'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_class_subjects_teacher_class_subjects'), table_name='teacher_class_subjects')
    op.drop_table('teacher_class_subjects')
    op.drop_index(op.f('ix_subject_class_subject_class_id'), table_name='subject_class')
    op.drop_table('subject_class')
    op.drop_index(op.f('ix_student_class_sc_id'), table_name='student_class')
    op.drop_table('student_class')
    op.drop_index(op.f('ix_student_parent_student_parent_id'), table_name='student_parent')
    op.drop_table('student_parent')
    op.drop_index(op.f('ix_class_sections_class_section_id'), table_name='class_sections')
    op.drop_table('class_sections')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_students_reg_no'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_sections_section_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_parents_parent_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_classes_class_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_schools_school_id'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
